### ISSUE TITLE
texture Draw(float x, float y)

### ISSUE THREAD

**Issue by ghost** [Margoulin/Vita3D#2]
[sample.zip](https://github.com/Margoulin/Vita3D/files/1240447/sample.zip)
Hey @Margoulin 
Nice job on the library, been using it for a project the last few months.
I'm having trouble using Vita3DTextureResource::Draw(float x, float y) with multiple textures.
drawing a single texture works great, but if i draw more than one texture (say GUI elements)
eg.
`texture1->Draw(20.0f, 20.0f);
texture2->Draw(880.0f, 20.0f);
texture3->Draw(200.0f, 20.0f);`

all 3 textures are drawn at texture3's position and scaled to texture3's size.
any idea why this might be?
I have attached the sample project with an extra ->Draw(x, y) call, as an example.

**Comment by Margoulin** [comment]
Hi
Thanks a lot for using my library.
I probably found the problem but currently I don't have a computer. 
So I'll fix the problem next week, when I could work again.

**Comment by ghost** [comment]
no worries at all. Thanks for the quick reply. :-)

**Comment by Margoulin** [comment]
Hi
So I pushed a fix. I've tested with two textures. So normally there's no problem with it anymore.
Thanks for seeing this issue

**Comment by ghost** [comment]
that's awesome, thanks for that. I'll get started on UI now.
